universe 		= docker
docker_image 		= pytorch/pytorch
executable              = inf.sh
output                  = project.out
error                   = project.err
log                     = proejct.log
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = inference.py
request_GPUs = 1
request_CPUs = 5
request_memory = 10G
requirements = UidDomain == "cs.uni-saarland.de" 
+WantGPUHomeMounted = true
queue 1
